GET http://localhost:3000/search/aaa

Content-Type:application/json

{
  "name": "John Doe",
  "email": "
}


###

POST http://localhost:3000/search
Content-Type:application/json

{
  "key": "土味"
}

###

GET http://localhost:8787

###
POST https://diabackend.drafff.workers.dev/search
Content-Type:application/json

{
  "key": "美丽"
}
